title: Esta es  mi pagina
author: Cristian
email: Cristian@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 qweqweqweqwewqeqwe


# social links
twitter_username: qwewqeqw # DO NOT include the @ character, or else the build will fail!
github_username:  qweqweqw # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
 
# Build settings 
theme: minima
 
